# Font
font_family      JetBrains Mono Nerd Font
font_size 11

# Transparency
background_opacity 0.50

# Padding (why weird value? consistency with foot)
window_margin_width 21.75

allow_remote_control yes
listen_on unix:@mykitty

# No stupid close confirmation
confirm_os_window_close 0

# Use fish shell
shell fish

remember_window_size no
initial_window_width 78c
initial_window_height 23c

# Copy
map ctrl+c    copy_or_interrupt
map page_up    scroll_page_up
map page_down  scroll_page_down
map ctrl+minus change_font_size all -1
map ctrl+0 change_font_size all 0

tab_bar_style separator
tab_separator ""
tab_bar_min_tabs 2
active_tab_font_style bold

map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9

map ctrl+t new_tab
map ctrl+w close_tab

map ctrl+shift+page_up move_tab_backward
map ctrl+shift+page_down move_tab_forward

include ~/.cache/lumen/kitty-colors.conf