[config]

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty.conf"
output_path = "~/.cache/ricelin/kitty-colors.conf"

[templates.starship]
input_path = "~/.config/matugen/templates/starship.toml"
output_path = "~/.config/starship.toml"
