# -----------------------
# Background & Foreground
# -----------------------

background {{surface}}
foreground {{bright}}

# Cursor

cursor {{primary}}
cursor_text_color background

# Selection

selection_background {{surface_container_high}}
selection_foreground {{bright}}

# URL

url_color {{primary}}

# Window borders

active_border_color {{primary}}
inactive_border_color {{outline_variant}}
bell_border_color {{primary}}

# Tabs

tab_bar_background {{surface}}

active_tab_background {{primary}}
active_tab_foreground {{bright}}

inactive_tab_background {{surface_container}}
inactive_tab_foreground {{subtle}}

# Marks

mark1_background {{primary}}
mark1_foreground {{bright}}

# Bell

visual_bell_color {{primary}}

# Wayland

wayland_titlebar_color background

